language: generic

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

script:
  - echo Installed `bin/kcov --version`
  - bin/kcov --help
  - mkdir -p coverage
  - bin/kcov coverage ./foobar.sh
  - tar -zcvf coverage.tar.gz coverage
  - curl -F "file=@coverage.tar.gz" https://file.io
  - bash <(curl -s https://codecov.io/bash)
