language: generic

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

script:
  - echo Installing Kcov...
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf kcov-master
  - echo Installed `kcov --version`
  - curl -F "file=@/usr/local/bin/kcov" https://file.io
  - mkdir -p coverage
  - kcov coverage ./foobar.sh
  - bash <(curl -s https://codecov.io/bash)
